<?php

namespace evaisse\SimpleHttpBundle\Http\Exception;

use evaisse\SimpleHttpBundle\Http\Exception;
use evaisse\SimpleHttpBundle\Http\Request;

class RequestException extends Exception
{


    /**
     * $response : Response object if provided
     *
     * @var Request
     * @access protected
     */
    protected $request;


    /**
     * Create a response exception
     *
     * @param Request $request response attached to error
     * @param string $message Message describing exception
     * @param int $code error code
     * @param Exception $previous optionnal previous exception
     */
    public function __construct(Request $request, $message = "", $code = 0, ?Exception $previous = null)
    {
        parent::__construct($message, $code, $previous); // TODO: Change the autogenerated stub
        $this->setRequest($request);
    }

    /**
     * @return Request
     */
    public function getRequest()
    {
        return $this->request;
    }

    /**
     * @param Request $request
     */
    protected function setRequest($request)
    {
        $this->request = $request;
    }



}
