<?php
/**
 * Created by PhpStorm.
 * User: evaisse
 * Date: 29/05/15
 * Time: 20:38
 */

namespace evaisse\SimpleHttpBundle\Http\Exception;

use evaisse\SimpleHttpBundle\Http\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;


class ResponseException extends HttpException
{

    /**
     * $response : Response object if provided
     *
     * @var ServiceResponse
     * @access protected
     */
    protected $response;


    /**
     * Create a response exception
     *
     * @param Response $response response attached to error
     * @param string $message Message describing exception
     * @param int $code error code
     * @param \Exception $previous optionnal previous exception
     */
    public function __construct(Response $response, $message = "", $code = 0, \Exception $previous = null)
    {
        parent::__construct($message, $code, $previous); // TODO: Change the autogenerated stub
        $this->setResponse($response);
    }

    /**
     * Set value for $response
     *
     * @param  Response $value value to set to response
     * @return Object          instance for method chaining
     */
    protected function setResponse(Response $value)
    {
        $this->response = $value;

        return $this;
    }

    /**
     * Get value for $response
     * @return ServiceResponse Response object if provided
     */
    public function getResponse()
    {
        return $this->response;
    }
}