language: php

php:
  - 8.0
  - 8.1

matrix:
  fast_finish: true


install:
  - composer install --no-interaction


script:
 - mkdir -p build/logs
 - php vendor/bin/phpunit


after_script:
 - php vendor/bin/coveralls -v
