services:

    http:
        alias: simple_http.helper


    simple_http.logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [simple_http]
        calls:
            - [pushHandler, ["@simple_http.logger.handler"]]

    simple_http.logger.handler:
        class: Monolog\Handler\StreamHandler
        arguments: [%kernel.root_dir%/logs/%kernel.environment%.log, 0]

    simple_http.helper:
        class:      evaisse\SimpleHttpBundle\Service\Helper
        arguments:  ["@service_container"]

    simple_http.kernel:
        class:      evaisse\SimpleHttpBundle\Http\Kernel
        arguments:  ["@service_container"]

    simple_http.profiler.data_collector:
        class: evaisse\SimpleHttpBundle\DataCollector\ProfilerDataCollector
        calls:
            - [ setStopWatch, [ "@debug.stopwatch" ] ]
        tags:
            - { name: data_collector, template: "SimpleHttpBundle:Collector:profiler", id: "simplehttpprofiler" }

    simple_http.twig.extension:
        class: evaisse\SimpleHttpBundle\Twig\Extension
        arguments: ["@twig.loader"]
        public: false
        tags:
            - { name: twig.extension }